### PR TITLE
Normalize all components

### PR DESCRIPTION
**Pull request by yanickrochon**
* Added `Grid` component.
* Renamed `GridRow` for `Row`
* Renamed `GridCol` for `Col`
* Added support for all grid / row / col classes.
* Added testing framework with basic tests.

Resolves issue #11

### CODE REVIEW

**Comment by imevro** [comment]
@sricho can you merge and publish new version? It looks pretty good

**Comment by sricho** [comment]
@evgenyrodionov @yanickrochon Apologies for dragging my feet on this. I completely forgot. I will review and merge ASAP.

**Comment by imevro** [comment]
@sricho very excited for this 👏🏻

**Comment by yanickrochon** [comment]
If anything, I will amend this PR with the necessary changes. Let me know!

**Pull request merged**
